name: Build students app for our demo

on:
  push:
    branches:
      - main
      - demo
    paths:
      - students_app/**

env:
  REGISTRY: registry.digitalocean.com
  REGISTRY_NAME: cashew
  IMAGE_NAME: students-app-demo

jobs:
  build-backend-for-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: ./students_app
    steps:
      - uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=v-