name: Build students app for our demo

on:
  push:
    branches:
      - main
      - demo
#    paths:
#      - students_app/**

env:
  REGISTRY: registry.digitalocean.com
  REGISTRY_NAME: cashew
  IMAGE_NAME: students-app-demo

jobs:
  build-backend-for-demo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        shell: bash
        working-directory: ./students_app
    steps:
      - uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=v-
      - name: set tag env
        run: echo "DOCKERTAG=$(echo ${{ steps.meta.outputs.tags }} | cut -d ':' -f2)" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DO_API_TOKEN }}
          password: ${{ secrets.DO_API_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./students_app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ github.sha }}